enzymes = {
    'arg-c':         [[/R/g, false]],
    'asp-n':         [[/\w(?=D)/g, false]],
    'bnps-skatole':  [[/W/g, false]],
    'caspase 1':     [[/D(?=[^PEDQKR])/g, "(?<=[FWYL]\w[HAT])"]],
    'caspase 2':     [[/D(?=[^PEDQKR])/g, "(?<=DVA)"]],
    'caspase 3':     [[/D(?=[^PEDQKR])/g, "(?<=DMQ)"]],
    'caspase 4':     [[/D(?=[^PEDQKR])/g, "(?<=LEV)"]],
    'caspase 5':     [[/D/g, "(?<=[LW]EH)"]],
    'caspase 6':     [[/D(?=[^PEDQKR])/g, "(?<=VE[HI])"]],
    'caspase 7':     [[/D(?=[^PEDQKR])/g, "(?<=DEV)"]],
    'caspase 8':     [[/D(?=[^PEDQKR])/g, "(?<=[IL]ET)"]],
    'caspase 9':     [[/D/g, "(?<=LEH)"]],
    'caspase 10':    [[/D/g, "(?<=IEA)"]],
    'chymotrypsin high specificity': [[/([FY](?=[^P]))|(W(?=[^MP]))/g, false]],
    'chymotrypsin low specificity': [[/([FLY](?=[^P]))|(W(?=[^MP]))|(M(?=[^PY]))|(H(?=[^DMPW]))/g, false]],
    'clostripain':   [[/R/g, false]],
    'cnbr':          [[/M/g, false]],
    'enterokinase':  [[/K/g, "(?<=[DE]{3})"]],
    'factor Xa':     [[/R/g, "(?<=[AFGILTVM][DE]G)"]],
    'formic acid':   [[/D/g, false]],
    'glutamyl endopeptidase': [[/E/g, false]],
    'granzyme B':    [[/D/g, "(?<=IEP)"]],
    'hydroxylamine': [[/N(?=G)/g, false]],
    'iodosobenzoic acid': [[/W/g, false]],
    'lysc':          [[/K/g, false]],
    'ntcb':          [[/\w(?=C)/g, false]],
    'pepsin ph2.0':  [[/([^R](?=[FLWY][^P]))|([FLWY](?=\w[^P]))/g, "(?<=[^HKR][^P])"]],
    'pepsin ph1.3':  [[/([^R](?=[FL][^P]))/g, "(?<=[^HKR][^P])"], [/([FL](?=\w[^P]))/g, "(?<=[^HKR][^P])"]],
    'proline endopeptidase': [[/P(?=[^P])/g, "(?<=[HKR])"]],
    'pronase':         [[/\w/g, false]],
    //'pronase E':     [[/[AFILVWY]/g, "(?<=[AFILVWY])"]],
    'proteinase K':  [[/[AEFILTVWY]/g, false]],
    'staphylococcal peptidase i': [[/E/g, "(?<=[^E])"]],
    'thermolysin':   [[/[^DE](?=[AFILMV])/g, false]],
    'thrombin':      [[/(R(?=G))/, "(?<=G)"], [/(R(?=[^DE][^DE]))/g, "(?<=[AFGILTVM][AFGILTVWA]P)"]],
    'trypsin':       [[/([KR](?=[^P]))/g, false], [/K(?=P)/g, "(?<=W)"],[/R(?=P)/g, "(?<=M)"]]
};
